### PR TITLE
fix Virtus module is deprecatation

### PR DESCRIPTION
**Pull request by leandroalemao**
PR to fix `including Virtus module is deprecated. Use 'include Virtus.model' instead` message.

### CODE REVIEW

**Review by karmajunkie — APPROVED** [review]
Thanks!

**Comment by leandroalemao** [comment]
Hi @karmajunkie Can you please merge the PR? I don't have write access to your repo. I think it needs fixing some conflicts due the changes are based in a previous version of `command.rb` file.. but not a big deal.. 2 seconds job.
Thank you so much
Leandro

**Comment by karmajunkie** [comment]
yep, looking at it now, thought i merged it previously but was on my cell phone.

**Comment by karmajunkie** [comment]
@leandroalemao you've made this PR against master, which is several commits ahead of this one.  I would have preferred it if you had rebased against master before making the PR or at least indicated which tag or commit it used as a base.  What I've done is apply it to the tagged version 0.2.0 and bumped the version to 0.2.1 and released an updated gem with your fix applied.

**Pull request closed without merging**
